schizo/ompi: update RST
openpmix/prrte pull request #1788
Opened 2023-09-10 23:45 UTC by jsquyres

The schizo-ompi-cli.rst file is now the only file that we're going to include downstream in Open MPI's documentation.

Update it to include a first cut of all of Open MPI's mpirun command line options (which, at least for the moment, are the same as the options available for prterun).

2023-09-11 18:05 UTC, rhc54 requested changes

2023-09-11 18:05 UTC, rhc54 commented on src/mca/schizo/ompi/schizo-ompi-cli.rst
> +The ``--add-host`` option
You probably don't want this as `mpirun` cannot extend the DVM since it is a one-shot operation.

2023-09-11 18:05 UTC, rhc54 commented on src/mca/schizo/ompi/schizo-ompi-cli.rst
> +The ``--add-hostfile`` option
Ditto here - you don't want this option

2023-09-11 18:05 UTC, rhc54 commented on src/mca/schizo/ompi/schizo-ompi-cli.rst
> +The ``--dvm`` option
You folks expressly requested that `mpirun` not support this option.

2023-09-11 18:05 UTC, rhc54 commented on src/mca/schizo/ompi/schizo-ompi-cli.rst
> +The ``--personality`` option
I don't think you want to expose this option as you want the personality "locked" to OMPI.

2023-09-11 23:27 UTC, jsquyres commented
@rhc54 Updated; thanks!

2023-09-11 23:50 UTC, rhc54 commented
Bah - you are missing a bunch of options. I should have looked more closely - my apologies.

Best way to do this is just to walk thru the `mpirun` cmd line definition in `schizo/ompi/schizo_ompi.c`, starting at line 94.  All the options are listed there, including things that have no PRRTE equivalent (and therefore will require your own custom verbage).

I'm also not sure how you are handling the single-character version of some of the options - do you capture those in the snippets? If so, what do you do about differences between the personalities when it comes to single character equivalents? You might accept something others don't, so we probably cannot put the single character equivalents in the snippets. Not sure how you want to handle those.

2023-09-12 01:59 UTC, jsquyres commented
I don't think that this is perfect, either, but I think I have most of the options now.

2023-09-14 14:00 UTC, rhc54 approved these changes

2023-09-14 14:01 UTC, rhc54 commented
Let's go ahead and commit this so I can perhaps do some cleanup on it while working over the docs in general. Sound okay?

2023-09-14 14:23 UTC, merged

2023-09-14 14:23 UTC, jsquyres commented
> Let's go ahead and commit this so I can perhaps do some cleanup on it while working over the docs in general. Sound okay?

Thank you, sir!