Fix attach assert in finalize
openpmix/prrte pull request #645
Opened 2020-09-22 21:50 UTC by jjhursey

A few items all related to cause this error.
 * In finalize we destruct the `prte_job_data` in a loop. Since we cannot know the order in which job items will be popped off of the hash it is possible that this tries to finalize the child job before the parent job. In a debug build this causes an assert in `prte_list_item_destruct` since we are destructing a list item that is a member of another list - namely the `children` list of the parent.
   - To fix this we need to first clear the children list from all jobs, before we destroy the job structures.
 * If the tool calls `PMIx_Query_info` with the qualifier `PMIX_NSPACE` that contains an unknown namespace (or bogus namespace) then the query function will create a job structure for it and add it to the list. If the `PMIX_NSPACE` is of the form `prterun-c712f6n0132359.0` then it will replace the `prte`/`prterun` daemon's entry in the `prte_job_data` hash orphaning the prior object. The prior object is the one that has a `children` list containing the application that was launched.
   - To fix this we need to (1) check the validity of the namespace passed to this function and return an error. (2) Make sure we do not create a new job structure for this bogus namespace which can confuse or, worse, overwrite good job structures in the hash table.
 * The `prte_plm_base_create_jobid` function will ensure that the `prte_job_t` structure passed to it is the one that is stored in the `prte_job_data` hash table at the new `jobid` position. This tightens up a window of time where the temporary object in the hash table (from `prte_convert_nspace_to_jobid` since this is a new jobid) is in the hash table instead of the actual `jdata` object passed to `prte_plm_base_create_jobid`.
 * Add some helper functions for the `prte_job_data` structure
   - `prte_set_job_data_object`
   - `prte_display_prte_job_data` debugging helper

2020-09-22 21:56 UTC, jjhursey commented
Thanks to all of the hard investigation and debug/dev work by @drwootton on this bug.
This became a bit more involved than we originally thought.

The problem was in the scenario below:

## Terminal 1:
```
shell$ prterun -np 2 --report-uri + ./hello 25
prterun-c712f6n0192502.0;tcp4://192.168.130.211:58522
```

## Terminal 2:
Using the `attach` program from PR https://github.com/openpmix/prrte/pull/639 in particular adding the `PMIX_NSPACE` qualifier [here](https://github.com/openpmix/prrte/pull/639/files#diff-56c516acc4c29620a92d36344deb4242R387-R389)
```
./attach prterun-c712f6n0192502.0
```

Note that the `.0` at the end should not be there since that is the `vpid` and not part of the namespace of the `prterun` command. This should fail in the `PMIx_Query_info` function for an invalid qualifier (it does now with this commit). Before this PR it would add a new `prte_job_t` object at position `0` overwriting the `prterun` job object that was there. This orphans the `.1` child causing an `assert` during finalize in the `prterun` process when it tries to free the `.1` object since it is on a list.

This PR fixes the blind addition of namespaces provided by tools via `PMIx_Query_info` qualifiers, and tightens up the setting of `prte_job_t` objects into the `prte_job_data` hash table.

2020-09-22 23:08 UTC, rhc54 requested changes
Hmmm...this doesn't feel right to me. It seems like we are making a lot of changes that aren't really necessary, just to deal with an incorrect input problem. Why not just resolve that problem with the changes made to `PMIx_Query_info`? If that was the only thing causing the finalize assert, then we are done - it's a classic case of fully protecting against user error.

Note that I have no issue with doing a more careful job of clearing out the job array during finalize - in fact, there really isn't any reason to do it at all. PRRTE is _only_ used by the daemons - no application uses any part of it, it isn't a library for others to link against, and thus there is no issue or value in chasing memory leaks at finalize. Thus, we don't need to do all this cleanup that can cause problems. All it does is generate potential code issues. Better to just strip it all out except for the places where we cleanup file systems. It is only there because ORTE used to be part of applications, and so it needed to completely cleanup.

My point is: rather than injecting a lot of code to deal with finalize, we should instead just remove code that isn't doing anything useful. Fix the input protection, and then let's take a more critical look at the rest to see what is really needed.

FWIW: there already was a "print job data object" function in the code base - has been for years. It is just `prte_dss.dump(0, jdata, PRTE_JOB)`. It is used throughout the code base whenever one needs to print the object for debug purposes. It is also used to generate the output for `--display-devel-map` so you get a complete picture of everything in the job object.

2020-09-23 11:13 UTC, drwootton approved these changes

2020-09-23 20:52 UTC, jjhursey commented
I'll see if I can slim this down a bit.

We broke it into a few separate commits to make it easier to pick what was needed.
 * (1st commit) I would like to keep the finalize cleanup. It was actually the place that caught the original problem, so might be handy in doing so again in the future since it doesn't hurt anything to keep it in place. I'll keep this commit sine it fixes finalze.
 * (2nd commit) I'll remove the second commit which updates to prte_hash_table.c which was adding some debug detection prints.
 * (3rd commit) I'd like to keep the clarifying comments in the third commit for the namespace. That one took a while to sort out so the comments are helpful for someone new to that code.
 * (4th commit) The 4th commit has the fix to check the input for PMIx_Query_info. So we will keep that.
 * (5th commit) The 5th commit does two things that I think we want.
   - First, it adds tightens up inserting the true `jdata` into `prte_plm_base_create_jobid`.
   - Second, it adds a `prte_set_job_data_object` setter function that will return the object replaced in the hash. This provides us with a pair to the `prte_get_job_data_object` function, and provides us with the opportunity to check to see if we replaced an object in the hash.
 * I'll remove the `prte_display_prte_job_data` function since it is not used and easy enough to rebuild if we ever need it.

I'm guessing that your comments were mostly directed at the 2nd and 5th commits or were there other concerns with the other commits?

2020-09-23 21:06 UTC, rhc54 commented
I honestly hadn't looked at it on a per-commit basis - I just reviewed the end point. We can revamp the finalize later, so I don't really care about the first commit. I don't understand what used to be the fifth commit (and is now the 4th one), nor why it is needed. Inserting into the job array is a pretty simple operation, and I'm not convinced what is being done in the commit is correct.

So I guess I'd suggest keeping the query_info patch as that is what addressed the problem. If you want the finalize cleanup and the clarifying notes, I can live with that for now - I'll remove the finalize cleanup when I return to PRRTE (it was on the list of things for housekeeping), and can then try better to understand what you noted. At that point, let's circle back around to whatever is going on with the job array.

2020-09-23 21:10 UTC, jjhursey commented
I reworked the PR a bit.
 * First commit fixes finalize.
 * Second commit fixes PMIx_Query_info
 * Third commit adds some clarifying comments - no code changes.
 * Last commit wraps the setting of the hash entry in a `prte_set_job_data_object` for parity with `prte_get_job_data_object` and tightens up `prte_plm_base_create_jobid`

I'm happy to discuss the last commit further. Would you prefer I put that one in a separate PR for discussion from the first three commits?

2020-09-23 21:12 UTC, rhc54 commented
> Would you prefer I put that one in a separate PR for discussion from the first three commits?

Yeah, let's do that - I'm probably just not seeing the problem that you are addressing. My concern is that it may be a problem caused by something else that isn't quite right, and so we are fixing a symptom instead of the problem.

2020-09-23 21:17 UTC, jjhursey commented
I pulled off the last commit into PR #647

2020-09-23 21:40 UTC, rhc54 approved these changes

2020-09-23 21:59 UTC, rhc54 commented
Looks like the travis failure to update successful build problem again.

2020-09-23 21:59 UTC, merged